# Generated by Django 6.0.6 on 2026-08-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proucts', '0009_cart_cartite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartIte',
            new_name='CartItem',
        ),
    ]
